name: Build and deploy to development

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_CLUSTER_NAME: eks-acg
  HELM_CHART_PATH: infra/helm
  ECR_REPOSITORY: bookstore-inventory-api  # Set as a workflow-level variable

jobs:
  build-and-deploy:
    name: Build, push, and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  # Use environment variable

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./build/git-update.sh -v major

      - name: Build, tag, and push image to ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -f src/Dockerfile -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG ./src
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Deploy to EKS with Helm
        run: |
          aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.AWS_CLUSTER_NAME }}
          helm upgrade --install inventory-api-development ${{ env.HELM_CHART_PATH }} \
            --namespace development \
            --set image.repository=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }},image.tag=$IMAGE_TAG
