name: Build and deploy to development

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: eks-acg
  HELM_CHART_PATH: infra/helm
  ECR_REPOSITORY: bookstore-inventory-api  # Set as a workflow-level variable

jobs:
  build-and-deploy:
    name: Build, push, and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: lakeside763/deploy-to-eks@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          eks-cluster-name: ${{ env.EKS_CLUSTER_NAME }}
          helm-chart-path: ${{ env.HELM_CHART_PATH }}
          ecr-registry: ${{ secrets.ECR_REGISTRY }}
          ecr-repository: ${{ env.ECR_REPOSITORY }}
    
        
