name: Build and deploy to development

on:
  workflow_dispatch:
  push: 
    branches:
      - main

env: 
  AWS_REGION: us-east-1
  AWS_CLUSTER_NAME: eks-acg
  HELM_CHART_PATH:  infra/helm

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./build/git-update.sh -v major

      - name:  Build, Tag, and Push the Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: bookstore-inventory-api
          IMAGE_TAG: latest
          #IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker build -f src/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./src
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # - name: Install helm
      #   uses: actions/setup-helm@v3
      #   with:
      #     helm-version: 3.9.0

      # - name: Update EKS kubeconfig
      #   uses: aws-actions/eks-update-kubeconfig@v1
      #   with: 
      #     cluster-name: eks-acg
      
      # - name: Deploy to EKS
      #   run: |
      #     aws eks --region us-east-1 update-kubeconfig --name eks-acg
      #     helm install bookstore-inventory-api infra/helm
      
      # - name: Deploy to EKS with Helm
      #   run: |
      #     aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}
      #     helm upgrade --install your-app ${{ env.HELM_CHART_PATH }} --set image.repository=${{ env.ECR_REGISTRY }}/your-app,image.tag=${{ github.sha }}

      - name: Deploy to EKS with Helm
        run: |
          aws eks --region us-east-1 update-kubeconfig --name eks-acg
          helm upgrade --install inventory-api-development ${{ env.HELM_CHART_PATH }} \
            --set image.repository=${{ env.ECR_REGISTRY }}/bookstore-inventory-api,image.tag=latest

    