name: Build and deploy to development

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'

# env:
#   AWS_REGION: us-east-1
#   EKS_CLUSTER_NAME: eks-acg
#   HELM_CHART_PATH: infra/helm
#   ECR_REPOSITORY: bookstore-inventory-api 

jobs:
  build-and-deploy:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_REF: ${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install NPM packages
        run: npm install
      
      - name: Parse Commit Message
        id: parse-message
        uses: ./.github/actions/parse-commit-message
        with:
          pattern: '^(fix|chore|feat!|feat|(docs|refactor|perf|styles))'

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ../build/git-update-tag.sh -v ${{ steps.parse-message.outputs.extracted_value }}
        

      # - name: Build and Deploy
      #   uses: ./.github/actions/build-deploy
      #   with:
      #     aws-region: ${{ env.AWS_REGION }}
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     eks-cluster-name: ${{ env.EKS_CLUSTER_NAME }}
      #     helm-chart-path: ${{ env.HELM_CHART_PATH }}
      #     ecr-registry: ${{ secrets.ECR_REGISTRY }}
      #     ecr-repository: ${{ env.ECR_REPOSITORY }}
      #     image-tag: ${{ steps.increment-git-tag.outputs.git-tag }}
    
        
